feat(action): introduce docker image build and push
moneymeets/moneymeets-composite-actions pull request #15
Opened 2023-11-29 14:50 UTC by IamAbbey

This PR introduces a shared docker image build and push action for our projects.

The concluded task [[1]](https://moneymeets.atlassian.net/browse/MD-7028) had duplicated build step across relevant project.

This PR aims to solve this.

Implemented herein
- Configurable push to ECR
- Cache management
- Dynamic tagging

2023-11-29 15:02 UTC, zyv reviewed
Just some wording suggestions.

2023-11-29 15:02 UTC, zyv commented on build-and-push-image/action.yml
> +    description: SSH auth sock
```suggestion
    description: SSH auth socket
```

2023-11-29 15:02 UTC, zyv commented on build-and-push-image/action.yml
> +    description: Depicts if the image should be pushed
```suggestion
    description: Determines whether the image should be pushed
```

2023-11-29 15:22 UTC, marns93 approved these changes
:+1: 
Nothing to add. We did a pre-review before and I think the action is good to go to use in our other repositories.

@IamAbbey 
So next step would be using this action in the repositories where you added the Dockerfiles. After we prepared the infrastructure we can update the default for `push_to_ecr` and all images will be pushed with next pipeline runs.

2023-11-30 08:18 UTC, marns93 requested changes
I've seen that the ssh_key is required, which is not true for moneymeets-backoffice app.

2023-11-30 08:18 UTC, marns93 commented on build-and-push-image/action.yml
> +    required: true
SSH key is optional. For instance moneymeets-backoffice is not using this.
```suggestion
    required: false
```

2023-11-30 08:18 UTC, marns93 commented on build-and-push-image/action.yml
> +    - name: Setup SSH agent
Should be executed if ssh_key is set

2023-11-30 08:18 UTC, marns93 commented on build-and-push-image/action.yml
> +        ssh: |
Not needed if `ssh_key` is not set

2023-11-30 12:29 UTC, marns93 approved these changes

2023-11-30 12:35 UTC, marns93 commented
/rebase

2023-11-30 12:37 UTC, marns93 commented
@IamAbbey We created the ECR repositories and added `APPLICATION_ID` to the repositories where you prepared the Dockerfiles.
So if you would like to, we can change the default for `push_to_ecr` to true and push the images.

In the other repository workflows you can use `ecr_repository: ${{ vars.APPLICATION_ID }}`.

2023-12-01 08:10 UTC, merged